name: Plus62 Store
title: Plus62 Store
description: Produk & Jasa Bordir Tasikmalaya
avatar: /assets/logo/icon.svg

breakingNews: Test New Site at Github

comen: 30234
sitekey: 6LdSeuwZAAAAAPgWy6REloO70SStpBewNGuGmTkG
fb-pixel: 
fb-appID: 
fb-admin: 
fb-profile: 
fb-pages: 
signal-id: 23925364-ab76-466d-b529-44ea74b5d7c1
google_analytics: UA-187631685-1
url:
baseurl: ""

permalink: products/:title

collections:
  blogs:
    output: true

defaults:
- scope:
    type: posts
  values:
    layout: product
- scope:
    type: pages
  values:
    layout: page
- scope:
    type: blogs
  values:
    layout: post

sidebar_options:
  - sidebar
  - no-sidebar

version: v4.2.0

kramdown:

  input: GFM

  syntax_highlighter: rouge
  syntax_highlighter_opts:

    css_class: 'highlight'

sass:
  style: :expanded

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: 
  instagram:
  linkedin:
  pinterest:
  rss: 
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
