name: Plus62 Store
title: Plus62 Store
description: Produk & Jasa Bordir Tasikmalaya
avatar: /assets/logo/icon.svg

breakingNews: Web Store Sedang Tahap Pengembangan, Namun kamu tetap bisa melakukan pembelian seperti biasa.

comen: 30234
sitekey: 6LdPL-wZAAAAAAzUvjEWXHGLAgKL78wBzB1IR8t7
fb-pixel: 791401205101923
fb-appID: 437300347340287
fb-admin: 158878762428839
fb-profile: 435671100899312
fb-pages: 107881477662203
signal-id: 6d1eb5cd-8c5d-4cf3-aa06-eed9c3e1aee0
safari-web-ID: web.onesignal.auto.0f4ef0fc-d020-4184-9066-253532c318fc
google_analytics: UA-187631685-1
url: 
baseurl: ""

permalink: products/:title

collections:
  blog-post:
    output: true

defaults:
- scope:
    type: posts
  values:
    layout: product
- scope:
    type: pages
  values:
    layout: page
- scope:
    type: blog-post
  values:
    layout: post

sidebar_options:
  - sidebar
  - no-sidebar

version: v4.2.0

kramdown:

  input: GFM

  syntax_highlighter: rouge
  syntax_highlighter_opts:

    css_class: 'highlight'

sass:
  style: :expanded

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: 
  instagram:
  linkedin:
  pinterest:
  rss: 
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 

compress_html:
  clippings: all
  ignore:
    envs: development

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
